name = "docfactory"
compatibility_date = "2025-01-01"

# Browser Rendering limits:
# Free plan: 10 min/day, 3 concurrent browsers
# Paid plan: 10 hours/month, 10 concurrent browsers
# Overage: $0.09/browser hour
